import java.io.IOException;
import java.net.MalformedURLException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.aksingh.owmjapis.CurrentWeather;
import net.aksingh.owmjapis.OpenWeatherMap;
import org.json.JSONException;
import javax.swing.JTextField;
import javax.swing.JTextArea;

public class hd extends javax.swing.JFrame {
    int i=0,sayac=0;
    
    /**
     * Creates new form hd
     */
    public hd() {
        initComponents();
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sehir_al_alanı = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        sehir_sil_alani = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea8 = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextArea9 = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextArea10 = new javax.swing.JTextArea();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTextArea11 = new javax.swing.JTextArea();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTextArea12 = new javax.swing.JTextArea();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTextArea13 = new javax.swing.JTextArea();
        jScrollPane14 = new javax.swing.JScrollPane();
        jTextArea14 = new javax.swing.JTextArea();
        jScrollPane15 = new javax.swing.JScrollPane();
        jTextArea15 = new javax.swing.JTextArea();
        jScrollPane16 = new javax.swing.JScrollPane();
        jTextArea16 = new javax.swing.JTextArea();
        jScrollPane17 = new javax.swing.JScrollPane();
        jTextArea17 = new javax.swing.JTextArea();
        jScrollPane18 = new javax.swing.JScrollPane();
        jTextArea18 = new javax.swing.JTextArea();
        jScrollPane19 = new javax.swing.JScrollPane();
        jTextArea19 = new javax.swing.JTextArea();
        jScrollPane20 = new javax.swing.JScrollPane();
        jTextArea20 = new javax.swing.JTextArea();
        jScrollPane21 = new javax.swing.JScrollPane();
        jTextArea21 = new javax.swing.JTextArea();
        jScrollPane22 = new javax.swing.JScrollPane();
        jTextArea22 = new javax.swing.JTextArea();
        jScrollPane23 = new javax.swing.JScrollPane();
        jTextArea23 = new javax.swing.JTextArea();
        jScrollPane24 = new javax.swing.JScrollPane();
        jTextArea24 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hava Durumu Servisi");
        setBackground(new java.awt.Color(153, 255, 153));
        setForeground(new java.awt.Color(204, 255, 204));
        setResizable(false);

        sehir_al_alanı.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sehir_al_alanı.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sehir_al_alanıActionPerformed(evt);
            }
        });
        sehir_al_alanı.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sehir_al_alanıKeyPressed(evt);
            }
        });

        jButton1.setText("EKLE");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        sehir_sil_alani.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sehir_sil_alani.setName(""); // NOI18N
        sehir_sil_alani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sehir_sil_alaniActionPerformed(evt);
            }
        });

        jButton2.setText("SİL");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(153, 255, 153));
        jScrollPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 153), 2, true));
        jScrollPane1.setForeground(new java.awt.Color(153, 255, 153));
        jScrollPane1.setToolTipText("");
        jScrollPane1.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jScrollPane1.setPreferredSize(new java.awt.Dimension(150, 86));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(102, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jTextArea1.setForeground(java.awt.Color.red);
        jTextArea1.setRows(3);
        jScrollPane1.setViewportView(jTextArea1);

        jScrollPane2.setBackground(new java.awt.Color(153, 255, 153));
        jScrollPane2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 153), 2, true));
        jScrollPane2.setForeground(new java.awt.Color(153, 255, 153));
        jScrollPane2.setToolTipText("");
        jScrollPane2.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jScrollPane2.setPreferredSize(new java.awt.Dimension(150, 86));

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(102, 255, 255));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jTextArea2.setForeground(java.awt.Color.red);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jScrollPane3.setBackground(new java.awt.Color(153, 255, 153));
        jScrollPane3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 153), 2, true));
        jScrollPane3.setForeground(new java.awt.Color(153, 255, 153));
        jScrollPane3.setToolTipText("");
        jScrollPane3.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jScrollPane3.setPreferredSize(new java.awt.Dimension(150, 86));

        jTextArea3.setEditable(false);
        jTextArea3.setBackground(new java.awt.Color(102, 255, 255));
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jTextArea3.setForeground(java.awt.Color.red);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        jScrollPane4.setBackground(new java.awt.Color(153, 255, 153));
        jScrollPane4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 153), 2, true));
        jScrollPane4.setForeground(new java.awt.Color(153, 255, 153));
        jScrollPane4.setToolTipText("");
        jScrollPane4.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jScrollPane4.setPreferredSize(new java.awt.Dimension(150, 86));

        jTextArea4.setEditable(false);
        jTextArea4.setBackground(new java.awt.Color(102, 255, 255));
        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jTextArea4.setForeground(java.awt.Color.red);
        jTextArea4.setRows(5);
        jScrollPane4.setViewportView(jTextArea4);

        jScrollPane5.setBackground(new java.awt.Color(153, 255, 153));
        jScrollPane5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 153), 2, true));
        jScrollPane5.setForeground(new java.awt.Color(153, 255, 153));
        jScrollPane5.setToolTipText("");
        jScrollPane5.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jScrollPane5.setPreferredSize(new java.awt.Dimension(150, 86));

        jTextArea5.setEditable(false);
        jTextArea5.setBackground(new java.awt.Color(102, 255, 255));
        jTextArea5.setColumns(20);
        jTextArea5.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jTextArea5.setForeground(java.awt.Color.red);
        jTextArea5.setRows(5);
        jScrollPane5.setViewportView(jTextArea5);

        jScrollPane6.setBackground(new java.awt.Color(153, 255, 153));
        jScrollPane6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 153), 2, true));
        jScrollPane6.setForeground(new java.awt.Color(153, 255, 153));
        jScrollPane6.setToolTipText("");
        jScrollPane6.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jScrollPane6.setPreferredSize(new java.awt.Dimension(150, 86));

        jTextArea6.setEditable(false);
        jTextArea6.setBackground(new java.awt.Color(102, 255, 255));
        jTextArea6.setColumns(20);
        jTextArea6.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jTextArea6.setForeground(java.awt.Color.red);
        jTextArea6.setRows(5);
        jScrollPane6.setViewportView(jTextArea6);

        jScrollPane7.setBackground(new java.awt.Color(153, 255, 153));
        jScrollPane7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 153), 2, true));
        jScrollPane7.setForeground(new java.awt.Color(153, 255, 153));
        jScrollPane7.setToolTipText("");
        jScrollPane7.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jScrollPane7.setPreferredSize(new java.awt.Dimension(150, 86));

        jTextArea7.setEditable(false);
        jTextArea7.setBackground(new java.awt.Color(255, 204, 255));
        jTextArea7.setColumns(20);
        jTextArea7.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jTextArea7.setForeground(new java.awt.Color(0, 51, 255));
        jTextArea7.setRows(5);
        jScrollPane7.setViewportView(jTextArea7);

        jScrollPane8.setBackground(new java.awt.Color(153, 255, 153));
        jScrollPane8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 153), 2, true));
        jScrollPane8.setForeground(new java.awt.Color(153, 255, 153));
        jScrollPane8.setToolTipText("");
        jScrollPane8.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jScrollPane8.setPreferredSize(new java.awt.Dimension(150, 86));

        jTextArea8.setEditable(false);
        jTextArea8.setBackground(new java.awt.Color(255, 204, 255));
        jTextArea8.setColumns(20);
        jTextArea8.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jTextArea8.setForeground(new java.awt.Color(0, 51, 255));
        jTextArea8.setRows(5);
        jScrollPane8.setViewportView(jTextArea8);

        jScrollPane9.setBackground(new java.awt.Color(153, 255, 153));
        jScrollPane9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 153), 2, true));
        jScrollPane9.setForeground(new java.awt.Color(153, 255, 153));
        jScrollPane9.setToolTipText("");
        jScrollPane9.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jScrollPane9.setPreferredSize(new java.awt.Dimension(150, 86));

        jTextArea9.setEditable(false);
        jTextArea9.setBackground(new java.awt.Color(255, 204, 255));
        jTextArea9.setColumns(20);
        jTextArea9.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jTextArea9.setForeground(new java.awt.Color(0, 51, 255));
        jTextArea9.setRows(5);
        jScrollPane9.setViewportView(jTextArea9);

        jScrollPane10.setBackground(new java.awt.Color(153, 255, 153));
        jScrollPane10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 153), 2, true));
        jScrollPane10.setForeground(new java.awt.Color(153, 255, 153));
        jScrollPane10.setToolTipText("");
        jScrollPane10.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jScrollPane10.setPreferredSize(new java.awt.Dimension(150, 86));

        jTextArea10.setEditable(false);
        jTextArea10.setBackground(new java.awt.Color(255, 204, 255));
        jTextArea10.setColumns(20);
        jTextArea10.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jTextArea10.setForeground(new java.awt.Color(0, 51, 255));
        jTextArea10.setRows(5);
        jScrollPane10.setViewportView(jTextArea10);

        jScrollPane11.setBackground(new java.awt.Color(153, 255, 153));
        jScrollPane11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 153), 2, true));
        jScrollPane11.setForeground(new java.awt.Color(153, 255, 153));
        jScrollPane11.setToolTipText("");
        jScrollPane11.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jScrollPane11.setPreferredSize(new java.awt.Dimension(150, 86));

        jTextArea11.setEditable(false);
        jTextArea11.setBackground(new java.awt.Color(255, 204, 255));
        jTextArea11.setColumns(20);
        jTextArea11.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jTextArea11.setForeground(new java.awt.Color(0, 51, 255));
        jTextArea11.setRows(5);
        jScrollPane11.setViewportView(jTextArea11);

        jScrollPane12.setBackground(new java.awt.Color(153, 255, 153));
        jScrollPane12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 153), 2, true));
        jScrollPane12.setForeground(new java.awt.Color(153, 255, 153));
        jScrollPane12.setToolTipText("");
        jScrollPane12.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jScrollPane12.setPreferredSize(new java.awt.Dimension(150, 86));

        jTextArea12.setEditable(false);
        jTextArea12.setBackground(new java.awt.Color(255, 204, 255));
        jTextArea12.setColumns(20);
        jTextArea12.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jTextArea12.setForeground(new java.awt.Color(0, 51, 255));
        jTextArea12.setRows(5);
        jScrollPane12.setViewportView(jTextArea12);

        jScrollPane13.setBackground(new java.awt.Color(153, 255, 153));
        jScrollPane13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 153), 2, true));
        jScrollPane13.setForeground(new java.awt.Color(153, 255, 153));
        jScrollPane13.setToolTipText("");
        jScrollPane13.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jScrollPane13.setPreferredSize(new java.awt.Dimension(150, 86));

        jTextArea13.setEditable(false);
        jTextArea13.setBackground(new java.awt.Color(153, 153, 255));
        jTextArea13.setColumns(20);
        jTextArea13.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jTextArea13.setRows(5);
        jScrollPane13.setViewportView(jTextArea13);

        jScrollPane14.setBackground(new java.awt.Color(153, 255, 153));
        jScrollPane14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 153), 2, true));
        jScrollPane14.setForeground(new java.awt.Color(153, 255, 153));
        jScrollPane14.setToolTipText("");
        jScrollPane14.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jScrollPane14.setPreferredSize(new java.awt.Dimension(150, 86));

        jTextArea14.setEditable(false);
        jTextArea14.setBackground(new java.awt.Color(153, 153, 255));
        jTextArea14.setColumns(20);
        jTextArea14.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jTextArea14.setRows(5);
        jScrollPane14.setViewportView(jTextArea14);

        jScrollPane15.setBackground(new java.awt.Color(153, 255, 153));
        jScrollPane15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 153), 2, true));
        jScrollPane15.setForeground(new java.awt.Color(153, 255, 153));
        jScrollPane15.setToolTipText("");
        jScrollPane15.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jScrollPane15.setPreferredSize(new java.awt.Dimension(150, 86));

        jTextArea15.setEditable(false);
        jTextArea15.setBackground(new java.awt.Color(153, 153, 255));
        jTextArea15.setColumns(20);
        jTextArea15.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jTextArea15.setRows(5);
        jScrollPane15.setViewportView(jTextArea15);

        jScrollPane16.setBackground(new java.awt.Color(153, 255, 153));
        jScrollPane16.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 153), 2, true));
        jScrollPane16.setForeground(new java.awt.Color(153, 255, 153));
        jScrollPane16.setToolTipText("");
        jScrollPane16.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jScrollPane16.setPreferredSize(new java.awt.Dimension(150, 86));

        jTextArea16.setEditable(false);
        jTextArea16.setBackground(new java.awt.Color(153, 153, 255));
        jTextArea16.setColumns(20);
        jTextArea16.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jTextArea16.setRows(5);
        jScrollPane16.setViewportView(jTextArea16);

        jScrollPane17.setBackground(new java.awt.Color(153, 255, 153));
        jScrollPane17.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 153), 2, true));
        jScrollPane17.setForeground(new java.awt.Color(153, 255, 153));
        jScrollPane17.setToolTipText("");
        jScrollPane17.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jScrollPane17.setPreferredSize(new java.awt.Dimension(150, 86));

        jTextArea17.setEditable(false);
        jTextArea17.setBackground(new java.awt.Color(153, 153, 255));
        jTextArea17.setColumns(20);
        jTextArea17.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jTextArea17.setRows(5);
        jScrollPane17.setViewportView(jTextArea17);

        jScrollPane18.setBackground(new java.awt.Color(153, 255, 153));
        jScrollPane18.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 153), 2, true));
        jScrollPane18.setForeground(new java.awt.Color(153, 255, 153));
        jScrollPane18.setToolTipText("");
        jScrollPane18.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jScrollPane18.setPreferredSize(new java.awt.Dimension(150, 86));

        jTextArea18.setEditable(false);
        jTextArea18.setBackground(new java.awt.Color(153, 153, 255));
        jTextArea18.setColumns(20);
        jTextArea18.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jTextArea18.setRows(5);
        jScrollPane18.setViewportView(jTextArea18);

        jScrollPane19.setBackground(new java.awt.Color(153, 255, 153));
        jScrollPane19.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 153), 2, true));
        jScrollPane19.setForeground(new java.awt.Color(153, 255, 153));
        jScrollPane19.setToolTipText("");
        jScrollPane19.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jScrollPane19.setPreferredSize(new java.awt.Dimension(150, 86));

        jTextArea19.setEditable(false);
        jTextArea19.setBackground(new java.awt.Color(255, 102, 255));
        jTextArea19.setColumns(20);
        jTextArea19.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jTextArea19.setForeground(new java.awt.Color(0, 102, 102));
        jTextArea19.setRows(5);
        jScrollPane19.setViewportView(jTextArea19);

        jScrollPane20.setBackground(new java.awt.Color(153, 255, 153));
        jScrollPane20.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 153), 2, true));
        jScrollPane20.setForeground(new java.awt.Color(153, 255, 153));
        jScrollPane20.setToolTipText("");
        jScrollPane20.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jScrollPane20.setPreferredSize(new java.awt.Dimension(150, 86));

        jTextArea20.setEditable(false);
        jTextArea20.setBackground(new java.awt.Color(255, 102, 255));
        jTextArea20.setColumns(20);
        jTextArea20.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jTextArea20.setForeground(new java.awt.Color(0, 102, 102));
        jTextArea20.setRows(5);
        jScrollPane20.setViewportView(jTextArea20);

        jScrollPane21.setBackground(new java.awt.Color(153, 255, 153));
        jScrollPane21.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 153), 2, true));
        jScrollPane21.setForeground(new java.awt.Color(153, 255, 153));
        jScrollPane21.setToolTipText("");
        jScrollPane21.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jScrollPane21.setPreferredSize(new java.awt.Dimension(150, 86));

        jTextArea21.setEditable(false);
        jTextArea21.setBackground(new java.awt.Color(255, 102, 255));
        jTextArea21.setColumns(20);
        jTextArea21.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jTextArea21.setForeground(new java.awt.Color(0, 102, 102));
        jTextArea21.setRows(5);
        jScrollPane21.setViewportView(jTextArea21);

        jScrollPane22.setBackground(new java.awt.Color(153, 255, 153));
        jScrollPane22.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 153), 2, true));
        jScrollPane22.setForeground(new java.awt.Color(153, 255, 153));
        jScrollPane22.setToolTipText("");
        jScrollPane22.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jScrollPane22.setPreferredSize(new java.awt.Dimension(150, 86));

        jTextArea22.setEditable(false);
        jTextArea22.setBackground(new java.awt.Color(255, 102, 255));
        jTextArea22.setColumns(20);
        jTextArea22.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jTextArea22.setForeground(new java.awt.Color(0, 102, 102));
        jTextArea22.setRows(5);
        jScrollPane22.setViewportView(jTextArea22);

        jScrollPane23.setBackground(new java.awt.Color(153, 255, 153));
        jScrollPane23.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 153), 2, true));
        jScrollPane23.setForeground(new java.awt.Color(153, 255, 153));
        jScrollPane23.setToolTipText("");
        jScrollPane23.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jScrollPane23.setPreferredSize(new java.awt.Dimension(150, 86));

        jTextArea23.setEditable(false);
        jTextArea23.setBackground(new java.awt.Color(255, 102, 255));
        jTextArea23.setColumns(20);
        jTextArea23.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jTextArea23.setForeground(new java.awt.Color(0, 102, 102));
        jTextArea23.setRows(5);
        jScrollPane23.setViewportView(jTextArea23);

        jScrollPane24.setBackground(new java.awt.Color(153, 255, 153));
        jScrollPane24.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 153), 2, true));
        jScrollPane24.setForeground(new java.awt.Color(153, 255, 153));
        jScrollPane24.setToolTipText("");
        jScrollPane24.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jScrollPane24.setPreferredSize(new java.awt.Dimension(150, 86));

        jTextArea24.setEditable(false);
        jTextArea24.setBackground(new java.awt.Color(255, 102, 255));
        jTextArea24.setColumns(20);
        jTextArea24.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jTextArea24.setForeground(new java.awt.Color(0, 102, 102));
        jTextArea24.setRows(5);
        jScrollPane24.setViewportView(jTextArea24);

        jButton3.setText("Yenile");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jLabel1.setText("Silmek için rakam giriniz. 1,2,3 gibi.");

        jLabel2.setText("Eklemek için şehir ismi giriniz. Eskişehir,Trabzon gibi.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jScrollPane23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 21, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jScrollPane24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(21, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sehir_al_alanı, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sehir_sil_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(sehir_al_alanı, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2)
                            .addComponent(sehir_sil_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sehir_al_alanıKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sehir_al_alanıKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_sehir_al_alanıKeyPressed

    
    //SEHİR EKLEME BUTONU
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        try {
            //Eklenecek sehri tanımlayıp kullanıcıdan alıyoruz.
            String Sehir=sehir_al_alanı.getText();
            //Sehri ve bilgileri ekrana yazdırıyoruz.
            SehirEkle(Sehir);
            //Ekledikten sonra, toplamda kac sehrin ekli olduğunu tutacak sayacı bir arttırıyoruz.
            sayac++;
            } catch (IOException ex) {
            Logger.getLogger(hd.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JSONException ex) {
            Logger.getLogger(hd.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    
    //SEHİR SİLME BUTONU
    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        SehirSil();
        
    }//GEN-LAST:event_jButton2MouseClicked

    private void sehir_sil_alaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sehir_sil_alaniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sehir_sil_alaniActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        try {
            Yenile();
        } catch (IOException ex) {
            Logger.getLogger(hd.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JSONException ex) {
            Logger.getLogger(hd.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void sehir_al_alanıActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sehir_al_alanıActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sehir_al_alanıActionPerformed

    
    
    public void Yenile()throws IOException, MalformedURLException, JSONException{
        JTextArea[] textAlanlari = {jTextArea1,jTextArea2,jTextArea3,jTextArea4,
            jTextArea5,jTextArea6,jTextArea7,jTextArea8,jTextArea9,jTextArea10,jTextArea11,jTextArea12,jTextArea13
            ,jTextArea14,jTextArea15,jTextArea16,jTextArea17,jTextArea18,jTextArea19,jTextArea20,jTextArea21
            ,jTextArea22,jTextArea23,jTextArea24};
        
       
            for(int i=0;i<sayac;i++){
                int b=textAlanlari[i].getText().length();
                if(b>1){
                    String[] x = textAlanlari[i].getText().split("\n");
                    textAlanlari[i].setText("");
                    SehirEkle(x[0]);
                }
                else
                    ;
            
            
            }
            
            
        
        
    }
            
    
    
   
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hd().setVisible(true);
            
            }
        });
    }

    
    
     
    
    
    public void SehirEkle(String A) 
            throws IOException, MalformedURLException, JSONException{
       
        
        //Sehir bilgilerini yazacagımız text alanlarını diziye atıyoruz.
        JTextArea[] textAlanlari = {jTextArea1,jTextArea2,jTextArea3,jTextArea4,
            jTextArea5,jTextArea6,jTextArea7,jTextArea8,jTextArea9,jTextArea10,jTextArea11,jTextArea12,jTextArea13
            ,jTextArea14,jTextArea15,jTextArea16,jTextArea17,jTextArea18,jTextArea19,jTextArea20,jTextArea21
            ,jTextArea22,jTextArea23,jTextArea24};
       
        
        
        //Keyimizi girerek apiye baglanıyoruz.
        OpenWeatherMap owm = new OpenWeatherMap("c6bdcdcf441bc44d08dd8643cf898f10");
        //Kullanıcıdan alınan şehir bilgisiyle şehrin tüm hava bilgilerini alıyoruz.
        CurrentWeather cwd = owm.currentWeatherByCityName(A);
        //a ve b değişkenlerine maks ve min sıcaklık değerlerini atıyoruz.
        float a = cwd.getMainInstance().getMinTemperature();
        float b = cwd.getMainInstance().getMaxTemperature();
        
        //Fahrenheiti Celciusa çeviriyoruz, floatı inte çeviriyoruz
        a = ((a - 32)*5)/9;
        b = ((b - 32)*5)/9;
        //Virgülden sonra iki basamaklı sayı formatı belirliyoruz.
        DecimalFormat df = new DecimalFormat("0.00");


        //5 text alanı oldugu için dögü 5 kere dönüyor. AL butonuna her basışta, her text alanını boş mu diye kontrol ediyor.
        //Boşsa bilgileri o text alanına yazıyor.
        //Değilse bir şey yapmıyor.
        
          for(int i=0;i<24;i++){
           //Text alanlarında bilgi olup olmadıgını kontrol ediyor. Sehir giriniz yazıyorsa veya boşsa alanda bilgi yoktur.
             if (cwd.hasCityName() && cwd.isValid()&& textAlanlari[i].getText().equals("") ){
                //Boş text alanına bilgileri yazıyor. Text alanına integer değer yazabilmek icin gerekli fonksiyonu kullanıyor.
                textAlanlari[i].setText(String.valueOf(A + "\nEn yüksek:" + df.format(b) + "C" + "\nEn düsük: " + df.format(a) + "C"));
                //Bos text alanına yazdıktan sonra döngüden çıkıyor.
                break;
             }
             //Text alanında bilgi varsa bir şey yapmayıp döngüyü devam ettiriyor.
             else
                ;
           
          }
          
        
        }
    
    
     
     public void SehirSil(){
         
         //Sehir bilgilerini yazacagımız text alanlarını diziye atıyoruz.
         JTextArea[] textAlanlari = {jTextArea1,jTextArea2,jTextArea3,jTextArea4,
            jTextArea5,jTextArea6,jTextArea7,jTextArea8,jTextArea9,jTextArea10,jTextArea11,jTextArea12,jTextArea13
            ,jTextArea14,jTextArea15,jTextArea16,jTextArea17,jTextArea18,jTextArea19,jTextArea20,jTextArea21
            ,jTextArea22,jTextArea23,jTextArea24};
         //Hangi şehrin silineceğini text alanından alıyoruz. Text alanından integer deger alabilmek için fonksiyon kullanıyoruz.
         int n = Integer.parseInt(sehir_sil_alani.getText());
         //Girlien text alanındaki bilgileri siliyoruz.
         textAlanlari[n-1].setText("");
         //Sildiğimiz şehrin ismini, şehirler dizisinde siliyoruz.
         
     
     }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JScrollPane jScrollPane24;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea10;
    private javax.swing.JTextArea jTextArea11;
    private javax.swing.JTextArea jTextArea12;
    private javax.swing.JTextArea jTextArea13;
    private javax.swing.JTextArea jTextArea14;
    private javax.swing.JTextArea jTextArea15;
    private javax.swing.JTextArea jTextArea16;
    private javax.swing.JTextArea jTextArea17;
    private javax.swing.JTextArea jTextArea18;
    private javax.swing.JTextArea jTextArea19;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea20;
    private javax.swing.JTextArea jTextArea21;
    private javax.swing.JTextArea jTextArea22;
    private javax.swing.JTextArea jTextArea23;
    private javax.swing.JTextArea jTextArea24;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextArea jTextArea7;
    private javax.swing.JTextArea jTextArea8;
    private javax.swing.JTextArea jTextArea9;
    private javax.swing.JTextField sehir_al_alanı;
    private javax.swing.JTextField sehir_sil_alani;
    // End of variables declaration//GEN-END:variables


}
